### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by ceoadlw** [symphonly/figaro#35]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Figaro'
2. It keeps showing Please login first without any instruction as to how to do it.
![image](https://user-images.githubusercontent.com/40710128/135562596-7067b4d6-10dc-427d-8b21-d090db4e5a13.png)

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by aquilla12** [comment]
I have the same issue. Here's my progress so far, if anyone else would like to add to it.
First off, I ran figaro from my console (admin makes no difference, same result) and got this error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "lib\server\__init__.py", line 89, in __start
  File "asyncio\base_events.py", line 587, in run_until_complete
  File "asyncio\tasks.py", line 630, in _wrap_awaitable
  File "site-packages\websockets\legacy\server.py", line 1071, in __await_impl__
  File "asyncio\base_events.py", line 1389, in create_server
OSError: [Errno 10013] error while attempting to bind on address ('127.0.0.1', 51966): an attempt was made to access a socket in a way forbidden by its access permissions
```
Since the figaro backend is not running because it has thrown an error, the GUI has nothing to connect to and hence I suspect we get the login message.
Now, the error seems to be caused by a port binding permission error in launching the server. I figured this kind of error would be logged in Event Viewer, and indeed it is. Here is the error that gets logged every time I try to start figaro:
```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user PC\Admin SID (S-1-5-21-914434207-167906464-2818121814-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```
Obviously, I have removed my full PC name for privacy reasons. The `AppID` and `CLSID` refer to the `PerAppRuntimeBroker`.
I have followed a guide found at https://shauncassells.wordpress.com/2015/09/28/windows-10-event-10016-fix-the-application-specific-permission-settings-do-not-grant-local-activation-permission-for-the-com-server-application-with-clsid-d63b10c5-bb46-4990-a94f-e40b9d520160-and-a/ that addresses a similar issue (with `RuntimeBroker`) and adapted it for the issue. Unfortunately, even after taking ownership in the registry and giving both `SYSTEM` and myself `Local Activation` and ` Local Launch` permissions through Component Services, and rebooting for good measure, I still get the login message, the permission error, and the system event.  If anyone more knowledgeable could shed some light here it would be much appreciated. 

It is possible that a manual installation and setup of figaro would be a workaround to solve the issue but I have yet to try this.

**Comment by aquilla12** [comment]
Update: my reboot failed because of a dialogue box. Done a proper reboot and figaro now works as expected
